services:
  ollama:
    volumes:
      - ./.ci_cache/ollama:/root/.ollama
  backend:
    volumes:
      - ./.ci_cache/chroma:/chroma
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
